---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/courses":
    get:
      summary: list courses
      tags:
      - Courses
      responses:
        '200':
          description: OK
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000/
