---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/courses":
    get:
      summary: List all courses
      tags:
      - Courses
      responses:
        '200':
          description: success
  "/api/v1/courses/{id}":
    get:
      summary: Retrieves a course
      tags:
      - Courses
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  description:
                    type: string
                  instructor_name:
                    type: string
                  image:
                    type: string
                  created_at:
                    type: string
                  updated_at:
                    type: string
                required:
                - id
                - title
                - description
                - instructor_name
                - image
        '404':
          description: not_found
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000/
